### ISSUE TITLE
Could not load JDBC driver class [oracle.jdbc.driver.OracleDriver] while using com.github.noraui ojdbc7 12.1.0.2

### ISSUE THREAD

**Issue by asankeg2000** [NoraUi/ojdbc7#3]
I may be not doing it right.

All I did in my project is use the below dependency in my pom.

```
		<dependency>
			<groupId>com.github.noraui</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>12.1.0.2</version>
		</dependency>
```
I am using Spring framework to acces my DB.

And I get the following.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.jdbc.datasource.SingleConnectionDataSource]: Factory method 'getDataSourcesXYZ' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [oracle.jdbc.driver.OracleDriver]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 42 more
Caused by: java.lang.IllegalStateException: Could not load JDBC driver class [oracle.jdbc.driver.OracleDriver]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.setDriverClassName(DriverManagerDataSource.java:130)
```

I can see the ojdbc7 jar in the class path.

But when I try to open the ojdbc7-12.1.0.2.jar in my .m2\repository\com\github\noraui\ojdbc7\12.1.0.2
it did not contain any oracle jars.

Am I missing something here?

Finally I did download oracle ojdbc14-10.2.0.4.0.jar to my .m2\repository\com\oracle\ojdbc14\10.2.0.4.0 and added the following dependency .

```
<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc14</artifactId>
			<version>10.2.0.4.0</version>
</dependency>
```

Which worked...!

Please let me know what I did wrong with noraui dependency?

**Comment by sgrillon14** [comment]
is it the same [issue 2](https://github.com/NoraUi/ojdbc7/issues/2)

https://oss.sonatype.org/content/repositories/releases/ repositories are supposed to be synchronized with the Central Repository but it seems not.

**Comment by ArKniiD** [comment]
Hello @asankeg2000,

As @sgrillon14 said, we fixed the jar a month ago but it is not synchronized from Sonatype on Maven Central.
We are going to release a new version of ojdbc (ojdbc8) by the end of the week. So you should be able to use it soon.
I suggest you a work around if you want to use the jar from sonatype : [https://oss.sonatype.org/service/local/repositories/releases/content/com/github/noraui/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar](https://oss.sonatype.org/service/local/repositories/releases/content/com/github/noraui/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar)

I guess you can set up you pom.xml by adding a repo to retrieve it from sonatype (https://oss.sonatype.org/service/local/repositories/releases)

Regards

**Comment by asankeg2000** [comment]
Hi @ArKniiD ,

It worked, I have updated the Jar in my local.

However, could you update when the repos are synced so that I can close this.

Thanks!

**Comment by ArKniiD** [comment]
Yes, I let you know when the new version is released.

Regards

**Comment by sgrillon14** [comment]
https://github.com/NoraUi/ojdbc8 ready on Maven Central:

```
<dependency>
    <groupId>com.github.noraui</groupId>
    <artifactId>ojdbc8</artifactId>
    <version>12.2.0.1</version>
</dependency>
```
